module.exports = Object.freeze({
  USER_LOADING: "USER_LOADING",
  USER_LOADED: "USER_LOADED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  AUTH_ERROR: "AUTH_ERROR",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  GET_ERRORS: "GET_ERRORS",
});
